'use strict';

/**
 * Owns the tmux + `systemd --user` side effects for a project.
 *
 * Invariants worth preserving:
 *  - Node always creates the tmux session *before* starting ttyd, so the tmux
 *    server never lands inside ttyd@<slug>.service's cgroup (see tmux.js).
 *  - Every method is idempotent. Re-running up() on a live project is a
 *    success; down() on a project that is already gone is a success.
 */

const fs = require('fs');
const fsp = fs.promises;
const net = require('net');
const path = require('path');

const config = require('./config');
const tmux = require('./tmux');
const systemd = require('./systemd');
const { HttpError } = require('./errors');
const { run } = require('./exec');

const isStub = () => false;

const envFilePath = (slug) => path.join(config.ENV_DIR, `${slug}.env`);

/**
 * systemd's EnvironmentFile parser accepts double-quoted values with
 * backslash escapes. Quoting means a cwd containing spaces or '#' survives.
 */
function envQuote(value) {
  if (/[\r\n\0]/.test(value)) throw new Error('environment value may not contain newlines');
  return `"${value.replace(/([\\"$`])/g, '\\$1')}"`;
}

/**
 * An interface name or an IP literal — nothing else can reach ttyd's -i.
 * ${WEBTERM_IFACE} expands to exactly one argument, so this cannot smuggle in a
 * second flag either way; the check is here to turn a typo into a clear error
 * instead of a unit that fails at start with ttyd's own terse message.
 */
function assertIface(iface) {
  if (!/^[A-Za-z0-9_.:%-]{1,64}$/.test(iface)) {
    throw new Error(`WEBTERM_TTYD_IFACE is not an interface name or address: ${iface}`);
  }
  return iface;
}

async function writeEnvFile(slug, { port, cwd, iface = config.TTYD_IFACE }) {
  const dest = envFilePath(slug);
  const body =
    `# generated by webterm — do not edit; rewritten on every project create\n` +
    `WEBTERM_SLUG=${envQuote(slug)}\n` +
    `WEBTERM_PORT=${envQuote(String(port))}\n` +
    `WEBTERM_IFACE=${envQuote(assertIface(iface))}\n` +
    `WEBTERM_CWD=${envQuote(cwd)}\n`;
  await fsp.mkdir(config.ENV_DIR, { recursive: true, mode: 0o700 });
  const tmp = `${dest}.${process.pid}.tmp`;
  await fsp.writeFile(tmp, body, { mode: 0o600 });
  await fsp.rename(tmp, dest);
}

async function removeEnvFile(slug) {
  await fsp.unlink(envFilePath(slug)).catch((err) => {
    if (err.code !== 'ENOENT') throw err;
  });
}

/** Is 127.0.0.1:<port> already bound by something? */
function portInUse(port) {
  return new Promise((resolve) => {
    const probe = net
      .createServer()
      .once('error', (err) => resolve(err.code === 'EADDRINUSE'))
      .once('listening', () => probe.close(() => resolve(false)))
      .listen(port, '127.0.0.1');
  });
}

async function which(bin) {
  const r = await run('sh', ['-c', `command -v -- "$1"`, 'sh', bin]).catch(() => null);
  return r && r.code === 0 ? r.stdout.trim() : null;
}

let preflightCache = null;
let preflightAt = 0;

/**
 * What can and cannot work on this host right now. Cached briefly so the
 * health endpoint and every create() don't re-shell out.
 */
async function preflight({ fresh = false } = {}) {
  if (!fresh && preflightCache && Date.now() - preflightAt < 10_000) return preflightCache;

  const problems = [];
  const [tmuxBin, ttydBin, sdProbe, linger] = await Promise.all([
    which('tmux'),
    which('ttyd'),
    systemd.probe(),
    systemd.lingerEnabled().catch(() => false),
  ]);
  const template = systemd.templateInstalled();

  if (!tmuxBin) problems.push({ id: 'tmux-missing', fatal: true, message: 'tmux is not on PATH' });
  if (!ttydBin) {
    problems.push({
      id: 'ttyd-missing',
      fatal: true,
      message: 'ttyd is not on PATH — see README "Installing ttyd"',
    });
  }
  if (!sdProbe.ok) {
    problems.push({ id: 'systemd-user-unreachable', fatal: true, message: sdProbe.reason });
  }
  if (!linger) {
    problems.push({
      id: 'linger-disabled',
      // Not fatal on its own: if a login session happens to exist, units work
      // until logout. It is still wrong for a headless VM.
      fatal: false,
      message:
        'lingering is disabled — user units will stop when you log out. ' +
        `Run: sudo loginctl enable-linger ${require('os').userInfo().username}`,
    });
  }
  if (!template) {
    problems.push({
      id: 'template-missing',
      fatal: false,
      message: `${systemd.TEMPLATE_NAME} is not installed in ${systemd.USER_UNIT_DIR} (webterm will install it on first use)`,
    });
  }

  preflightCache = {
    ok: !problems.some((p) => p.fatal),
    tmux: tmuxBin,
    tmux_version: await tmux.version(),
    ttyd: ttydBin,
    systemd_user: sdProbe.ok ? sdProbe.state : false,
    linger,
    template_installed: template,
    problems,
  };
  preflightAt = Date.now();
  return preflightCache;
}

function invalidatePreflight() {
  preflightCache = null;
}

async function assertUsable() {
  const pf = await preflight();
  if (pf.ok) return pf;
  const fatal = pf.problems.filter((p) => p.fatal).map((p) => p.message);
  throw new HttpError(503, `host is not ready to run project terminals: ${fatal.join('; ')}`, {
    problems: pf.problems,
  });
}

/**
 * Bring project <slug> up: env file, detached tmux session, ttyd unit.
 * @returns {Promise<{tmux: string, unit: string, port: number}>}
 */
async function up({ slug, port, cwd }) {
  await assertUsable();

  // Install the shipped template on first use, but never clobber a local edit.
  if (!systemd.templateInstalled()) {
    const how = await systemd.installTemplate();
    console.log(`[supervisor] ${systemd.TEMPLATE_NAME} ${how} in ${systemd.USER_UNIT_DIR}`);
    invalidatePreflight();
  }

  const unitState = await systemd.activeState(slug);
  if (unitState !== 'active' && unitState !== 'activating' && (await portInUse(port))) {
    throw new HttpError(
      409,
      `port ${port} is already bound by another process; refusing to start ttyd@${slug}`
    );
  }

  await writeEnvFile(slug, { port, cwd });
  const tmuxResult = await tmux.ensureSession(slug, cwd);
  const unitResult = await systemd.enableStart(slug);

  // enable --now returns before ttyd has necessarily bound its socket; confirm.
  const state = await waitForActive(slug, 5000);
  if (state !== 'active') {
    const log = await systemd.journalTail(slug);
    throw new HttpError(500, `ttyd@${slug}.service did not become active (state: ${state})`, {
      journal: log || '(no journal output)',
    });
  }

  return { tmux: tmuxResult, unit: unitResult, port };
}

async function waitForActive(slug, timeoutMs) {
  const deadline = Date.now() + timeoutMs;
  let state = await systemd.activeState(slug);
  while (state !== 'active' && state !== 'failed' && Date.now() < deadline) {
    await new Promise((r) => setTimeout(r, 150));
    state = await systemd.activeState(slug);
  }
  return state;
}

/**
 * Tear project <slug> down. Best-effort on every step: a partial teardown must
 * not leave the caller unable to retry, so failures are collected, not thrown,
 * unless nothing at all could be done.
 */
async function down({ slug }) {
  const result = { unit: 'skipped', tmux: 'skipped', env: 'skipped', errors: [] };

  const pf = await preflight();
  if (pf.systemd_user) {
    try {
      result.unit = await systemd.disableStop(slug);
    } catch (err) {
      result.errors.push(`unit: ${err.message}`);
    }
  } else {
    result.unit = 'systemd-unavailable';
  }

  try {
    result.tmux = await tmux.killSession(slug);
  } catch (err) {
    result.errors.push(`tmux: ${err.message}`);
  }

  try {
    await removeEnvFile(slug);
    result.env = 'removed';
  } catch (err) {
    result.errors.push(`env: ${err.message}`);
  }

  if (result.errors.length) console.warn(`[supervisor] down(${slug}) partial:`, result.errors);
  return result;
}

/**
 * Type `text` into the project's tmux pane. Deliberately routed through tmux
 * rather than the ttyd WebSocket (spec §3.5): it reaches the session whichever
 * client is attached, and webterm never has to track individual sockets.
 */
async function inject({ slug, text }) {
  await tmux.sendKeysLiteral(slug, text);
  return { injected: true };
}

/** Liveness for one project. Never throws. */
async function status(slug) {
  const [unit, sessions] = await Promise.all([
    systemd.activeState(slug).catch(() => 'unknown'),
    tmux.listSessions().catch(() => null),
  ]);
  return { unit, tmux: sessions === null ? null : sessions.includes(slug) };
}

/**
 * Liveness for many projects in two subprocess calls rather than 2N.
 * @returns {Promise<Map<string,{unit:string,tmux:boolean|null}>>}
 */
async function statusAll(slugs) {
  const [units, sessions] = await Promise.all([
    systemd.activeStates(slugs).catch(() => new Map()),
    tmux.listSessions().catch(() => null),
  ]);
  const live = sessions === null ? null : new Set(sessions);
  return new Map(
    slugs.map((s) => [
      s,
      { unit: units.get(s) || 'unknown', tmux: live === null ? null : live.has(s) },
    ])
  );
}

/**
 * WEBTERM_STUB_SUPERVISOR=1 skips every tmux/systemd side effect. Used by the
 * API tests and handy for frontend work on a machine with no ttyd. It is
 * announced loudly at boot so it can never be mistaken for the real thing.
 */
const stub = {
  up: async ({ slug, port, cwd }) => {
    console.log(`[supervisor:stub] up slug=${slug} port=${port} cwd=${cwd}`);
    return { tmux: 'stubbed', unit: 'stubbed', port };
  },
  down: async ({ slug }) => {
    console.log(`[supervisor:stub] down slug=${slug}`);
    return { unit: 'stubbed', tmux: 'stubbed', env: 'stubbed', errors: [] };
  },
  // Recorded rather than sent, so tests can assert the exact keystrokes.
  inject: async ({ slug, text }) => {
    stub._injected.push({ slug, text });
    console.log(`[supervisor:stub] inject slug=${slug} text=${JSON.stringify(text)}`);
    return { injected: true, stub: true };
  },
  _injected: [],
  status: async () => ({ unit: 'stubbed', tmux: null }),
  statusAll: async (slugs) => new Map(slugs.map((s) => [s, { unit: 'stubbed', tmux: null }])),
  preflight: async () => ({ ok: true, stub: true, problems: [], tmux: null, ttyd: null }),
  invalidatePreflight: () => {},
  isStub: () => true,
  envFilePath,
  _envQuote: envQuote,
  _assertIface: assertIface,
  _portInUse: portInUse,
};

const real = {
  up,
  down,
  inject,
  status,
  statusAll,
  preflight,
  invalidatePreflight,
  isStub,
  envFilePath,
  _envQuote: envQuote,
  _assertIface: assertIface,
  _portInUse: portInUse,
};

module.exports = config.STUB_SUPERVISOR ? stub : real;
